import type { CausalRule } from '../types';

// 개념 노드 규칙 (rc01~rc13)
export const conceptRules: CausalRule[] = [
  // ──────────────────────────────────────────────
  // 개념 노드: 입력 → 개념
  // ──────────────────────────────────────────────
  {
    id: 'rc01',
    source: 'kr_inflation',
    target: 'inflation_pressure',
    weight: 1.0,
    direction: 'positive',
    lag: 'immediate',
    explanation: '물가 상승은 인플레이션 압력을 높입니다.',
  },
  {
    id: 'rc02',
    source: 'oil',
    target: 'inflation_pressure',
    weight: 0.4,
    direction: 'positive',
    lag: 'immediate',
    explanation: '유가 상승은 수입물가를 통해 인플레이션 압력을 높입니다.',
  },
  {
    id: 'rc03',
    source: 'kr_growth',
    target: 'growth_pressure',
    weight: 1.0,
    direction: 'positive',
    lag: 'immediate',
    explanation: '경제성장률 상승은 경기 과열 압력을 높입니다.',
  },
  {
    id: 'rc04',
    source: 'kr_inflation',
    target: 'bok_stance',
    weight: 0.4,
    direction: 'positive',
    lag: 'immediate',
    explanation: '물가 상승은 중앙은행의 긴축 성향을 강화합니다.',
  },
  {
    id: 'rc05',
    source: 'us_rate',
    target: 'bok_stance',
    weight: 0.3,
    direction: 'positive',
    lag: 'immediate',
    explanation: '미국 금리 인상은 한국 금리 인상 압력으로 파급됩니다.',
  },
  {
    id: 'rc06',
    source: 'kr_growth',
    target: 'bok_stance',
    weight: 0.15,
    direction: 'positive',
    lag: 'immediate',
    explanation: '경기 과열은 중앙은행의 긴축 스탠스를 강화합니다.',
  },
  {
    id: 'rc07',
    source: 'kr_inflation',
    target: 'market_expectation',
    weight: 0.6,
    direction: 'positive',
    lag: 'immediate',
    explanation: '물가 상승은 시장의 금리 인상 기대를 강화합니다.',
  },
  {
    id: 'rc08',
    source: 'kr_growth',
    target: 'market_expectation',
    weight: 0.3,
    direction: 'positive',
    lag: 'immediate',
    explanation: '경기 과열은 시장의 금리 인상 기대를 높입니다.',
  },
  {
    id: 'rc09',
    source: 'usdkrw',
    target: 'market_expectation',
    weight: 0.15,
    direction: 'positive',
    lag: 'immediate',
    explanation: '환율 불안은 시장의 금리 인상 기대를 자극합니다.',
  },

  // ──────────────────────────────────────────────
  // 개념 노드: 개념 → 결과
  // ──────────────────────────────────────────────
  {
    id: 'rc10',
    source: 'bok_stance',
    target: 'kr_rate',
    weight: 1.0,
    direction: 'positive',
    lag: 'short',
    explanation: '중앙은행의 긴축 스탠스는 기준금리 인상으로 이어집니다.',
  },
  {
    id: 'rc11',
    source: 'inflation_pressure',
    target: 'kr_rate_pressure',
    weight: 0.42,
    direction: 'positive',
    lag: 'immediate',
    explanation: '인플레이션 압력은 시장금리 상승으로 이어집니다.',
  },
  {
    id: 'rc12',
    source: 'growth_pressure',
    target: 'kr_rate_pressure',
    weight: 0.21,
    direction: 'positive',
    lag: 'short',
    explanation: '경기 압력은 시장금리 상승 압력을 만듭니다.',
  },
  {
    id: 'rc13',
    source: 'market_expectation',
    target: 'kr_rate_pressure',
    weight: 0.3,
    direction: 'positive',
    lag: 'immediate',
    explanation: '시장의 금리 인상 기대는 시장금리를 먼저 끌어올립니다.',
  },

  // ──────────────────────────────────────────────
  // 한국 주식 개념 노드: 입력 → 개념
  // ──────────────────────────────────────────────
  {
    id: 'rsk01',
    source: 'kr_growth',
    target: 'earnings_outlook_kr',
    weight: 1.0,
    direction: 'positive',
    lag: 'immediate',
    explanation: '경제성장률 상승은 기업 실적 기대를 높입니다.',
  },
  {
    id: 'rsk02',
    source: 'oil',
    target: 'earnings_outlook_kr',
    weight: 0.4,
    direction: 'negative',
    lag: 'immediate',
    explanation: '유가 상승은 기업 비용 부담을 높여 실적 기대를 낮춥니다.',
  },
  {
    id: 'rsk03',
    source: 'kr_rate',
    target: 'discount_burden_kr',
    weight: 0.7,
    direction: 'positive',
    lag: 'immediate',
    explanation: '기준금리 상승은 할인율 부담을 키웁니다.',
  },
  {
    id: 'rsk04',
    source: 'kr_inflation',
    target: 'discount_burden_kr',
    weight: 0.5,
    direction: 'positive',
    lag: 'immediate',
    explanation: '물가 상승은 금리 인상 기대를 통해 할인율 부담을 높입니다.',
  },
  {
    id: 'rsk05',
    source: 'usdkrw',
    target: 'foreign_demand_kr',
    weight: 0.8,
    direction: 'negative',
    lag: 'immediate',
    explanation: '원화 약세는 외국인 투자자의 이탈 압력을 높입니다.',
  },
  {
    id: 'rsk06',
    source: 'us_rate',
    target: 'foreign_demand_kr',
    weight: 0.5,
    direction: 'negative',
    lag: 'immediate',
    explanation: '미국 금리 인상은 외국인 자금을 미국으로 끌어갑니다.',
  },

  // 한국 주식: 개념 → 개념
  {
    id: 'rsk07',
    source: 'earnings_outlook_kr',
    target: 'sentiment_kr',
    weight: 0.3,
    direction: 'positive',
    lag: 'immediate',
    explanation: '실적 기대 개선은 투자 심리를 높입니다.',
  },
  {
    id: 'rsk08',
    source: 'foreign_demand_kr',
    target: 'sentiment_kr',
    weight: 0.3,
    direction: 'positive',
    lag: 'immediate',
    explanation: '외국인 매수는 투자 심리를 개선합니다.',
  },
  {
    id: 'rsk09',
    source: 'discount_burden_kr',
    target: 'sentiment_kr',
    weight: 0.3,
    direction: 'negative',
    lag: 'immediate',
    explanation: '할인율 부담은 투자 심리를 위축시킵니다.',
  },

  // 한국 주식: 개념 → 결과
  {
    id: 'rsk10',
    source: 'earnings_outlook_kr',
    target: 'kr_stock',
    weight: 0.35,
    direction: 'positive',
    lag: 'short',
    explanation: '기업 실적 기대 개선은 주가 상승 압력을 만듭니다.',
  },
  {
    id: 'rsk11',
    source: 'discount_burden_kr',
    target: 'kr_stock',
    weight: 0.3,
    direction: 'negative',
    lag: 'short',
    explanation: '할인율 부담은 주가 하락 압력을 만듭니다.',
  },
  {
    id: 'rsk12',
    source: 'foreign_demand_kr',
    target: 'kr_stock',
    weight: 0.3,
    direction: 'positive',
    lag: 'short',
    explanation: '외국인 수급 개선은 주가에 긍정적입니다.',
  },
  {
    id: 'rsk13',
    source: 'sentiment_kr',
    target: 'kr_stock',
    weight: 0.2,
    direction: 'positive',
    lag: 'immediate',
    explanation: '투자 심리 개선은 즉시 주가에 반영됩니다.',
  },

  // ──────────────────────────────────────────────
  // 미국 주식 개념 노드: 입력 → 개념
  // ──────────────────────────────────────────────
  {
    id: 'rsu01',
    source: 'us_growth',
    target: 'earnings_outlook_us',
    weight: 1.0,
    direction: 'positive',
    lag: 'immediate',
    explanation: '미국 경제성장률 상승은 기업 실적 기대를 높입니다.',
  },
  {
    id: 'rsu02',
    source: 'oil',
    target: 'earnings_outlook_us',
    weight: 0.3,
    direction: 'negative',
    lag: 'immediate',
    explanation: '유가 상승은 기업 비용 부담을 높입니다.',
  },
  {
    id: 'rsu03',
    source: 'us_rate',
    target: 'discount_burden_us',
    weight: 0.8,
    direction: 'positive',
    lag: 'immediate',
    explanation: '미국 금리 인상은 할인율 부담을 키웁니다.',
  },
  {
    id: 'rsu04',
    source: 'us_inflation',
    target: 'discount_burden_us',
    weight: 0.5,
    direction: 'positive',
    lag: 'immediate',
    explanation: '물가 상승은 금리 인상 기대를 통해 할인율 부담을 높입니다.',
  },
  {
    id: 'rsu05',
    source: 'risk',
    target: 'sentiment_us',
    weight: 0.6,
    direction: 'negative',
    lag: 'immediate',
    explanation: '위험회피 심리 확산은 투자 심리를 위축시킵니다.',
  },

  // 미국 주식: 개념 → 개념
  {
    id: 'rsu06',
    source: 'earnings_outlook_us',
    target: 'sentiment_us',
    weight: 0.3,
    direction: 'positive',
    lag: 'immediate',
    explanation: '실적 기대 개선은 투자 심리를 높입니다.',
  },
  {
    id: 'rsu07',
    source: 'discount_burden_us',
    target: 'sentiment_us',
    weight: 0.3,
    direction: 'negative',
    lag: 'immediate',
    explanation: '할인율 부담은 투자 심리를 위축시킵니다.',
  },

  // 미국 주식: 개념 → 결과
  {
    id: 'rsu08',
    source: 'earnings_outlook_us',
    target: 'us_stock',
    weight: 0.4,
    direction: 'positive',
    lag: 'short',
    explanation: '기업 실적 기대 개선은 주가 상승 압력을 만듭니다.',
  },
  {
    id: 'rsu09',
    source: 'discount_burden_us',
    target: 'us_stock',
    weight: 0.35,
    direction: 'negative',
    lag: 'short',
    explanation: '할인율 부담은 주가 하락 압력을 만듭니다.',
  },
  {
    id: 'rsu10',
    source: 'sentiment_us',
    target: 'us_stock',
    weight: 0.25,
    direction: 'positive',
    lag: 'immediate',
    explanation: '투자 심리 개선은 즉시 주가에 반영됩니다.',
  },

  // ──────────────────────────────────────────────
  // 한국 채권 개념 노드: 입력 → 개념
  // ──────────────────────────────────────────────
  {
    id: 'rbk01',
    source: 'kr_rate',
    target: 'rate_burden_kr',
    weight: 0.8,
    direction: 'positive',
    lag: 'immediate',
    explanation: '기준금리 상승은 채권 금리 부담을 높입니다.',
  },
  {
    id: 'rbk02',
    source: 'kr_inflation',
    target: 'rate_burden_kr',
    weight: 0.5,
    direction: 'positive',
    lag: 'immediate',
    explanation: '물가 상승은 금리 인상 기대를 통해 금리 부담을 높입니다.',
  },
  {
    id: 'rbk03',
    source: 'kr_growth',
    target: 'credit_condition_kr',
    weight: 0.7,
    direction: 'positive',
    lag: 'short',
    explanation: '경제성장률 상승은 기업·국가 신용을 개선합니다.',
  },
  {
    id: 'rbk04',
    source: 'kr_inflation',
    target: 'credit_condition_kr',
    weight: 0.4,
    direction: 'negative',
    lag: 'immediate',
    explanation: '과도한 물가 상승은 재정 부담으로 신용을 악화시킵니다.',
  },
  {
    id: 'rbk05',
    source: 'usdkrw',
    target: 'foreign_bond_demand_kr',
    weight: 0.7,
    direction: 'negative',
    lag: 'immediate',
    explanation: '원화 약세는 외국인 채권 투자 매력을 낮춥니다.',
  },
  {
    id: 'rbk06',
    source: 'us_rate',
    target: 'foreign_bond_demand_kr',
    weight: 0.5,
    direction: 'negative',
    lag: 'immediate',
    explanation: '미국 금리 인상은 외국인 자금을 미국으로 끌어갑니다.',
  },

  // 한국 채권: 개념 → 결과
  {
    id: 'rbk07',
    source: 'rate_burden_kr',
    target: 'kr_bond',
    weight: 0.45,
    direction: 'negative',
    lag: 'immediate',
    explanation: '금리 부담은 채권 가격 하락 압력을 만듭니다.',
  },
  {
    id: 'rbk08',
    source: 'credit_condition_kr',
    target: 'kr_bond',
    weight: 0.3,
    direction: 'positive',
    lag: 'short',
    explanation: '신용 상태 개선은 채권 가격 상승 압력을 줍니다.',
  },
  {
    id: 'rbk09',
    source: 'foreign_bond_demand_kr',
    target: 'kr_bond',
    weight: 0.25,
    direction: 'positive',
    lag: 'short',
    explanation: '외국인 채권 수요 증가는 가격 상승 압력을 줍니다.',
  },

  // ──────────────────────────────────────────────
  // 미국 채권 개념 노드: 입력 → 개념
  // ──────────────────────────────────────────────
  {
    id: 'rbu01',
    source: 'us_rate',
    target: 'rate_burden_us',
    weight: 0.8,
    direction: 'positive',
    lag: 'immediate',
    explanation: '미국 금리 인상은 채권 금리 부담을 높입니다.',
  },
  {
    id: 'rbu02',
    source: 'us_inflation',
    target: 'rate_burden_us',
    weight: 0.5,
    direction: 'positive',
    lag: 'immediate',
    explanation: '물가 상승은 금리 인상 기대를 통해 금리 부담을 높입니다.',
  },
  {
    id: 'rbu03',
    source: 'us_growth',
    target: 'credit_condition_us',
    weight: 0.7,
    direction: 'positive',
    lag: 'short',
    explanation: '경제성장률 상승은 기업 신용을 개선합니다.',
  },
  {
    id: 'rbu04',
    source: 'oil',
    target: 'credit_condition_us',
    weight: 0.3,
    direction: 'negative',
    lag: 'short',
    explanation: '유가 상승은 기업 비용 부담을 통해 신용을 악화시킵니다.',
  },
  {
    id: 'rbu05',
    source: 'risk',
    target: 'safe_haven_demand',
    weight: 0.8,
    direction: 'positive',
    lag: 'immediate',
    explanation: '위험회피 심리 확산은 미국 국채 안전자산 수요를 높입니다.',
  },

  // 미국 채권: 개념 → 결과
  {
    id: 'rbu06',
    source: 'rate_burden_us',
    target: 'us_bond',
    weight: 0.45,
    direction: 'negative',
    lag: 'immediate',
    explanation: '금리 부담은 채권 가격 하락 압력을 만듭니다.',
  },
  {
    id: 'rbu07',
    source: 'credit_condition_us',
    target: 'us_bond',
    weight: 0.3,
    direction: 'positive',
    lag: 'short',
    explanation: '신용 상태 개선은 채권 가격 상승 압력을 줍니다.',
  },
  {
    id: 'rbu08',
    source: 'safe_haven_demand',
    target: 'us_bond',
    weight: 0.35,
    direction: 'positive',
    lag: 'immediate',
    explanation: '안전자산 수요 증가는 미국 국채 가격 상승 압력을 줍니다.',
  },
];
